<?php
session_start();
  define("S_CADASTRO_CANDIDATO",1);
  define("S_CADASTRO_PROFISSAO",2);
  define("S_CADASTRO_PERFIL",3);
  define("S_CADASTRO_USUARIO",4);
  define("S_PESQUISA_CANDIDATO",5);
  define("S_PESQUISA_PROFISSAO",6);
  define("S_PESQUISA_PERFIL",7);
  define("S_PESQUISA_USUARIO",8);
  define("S_ALTERACAO_CANDIDATO",9);
  define("S_ALTERACAO_PROFISSAO",10);
  define("S_ALTERACAO_PERFIL",11);
  define("S_ALTERACAO_USUARIO",12);
  define("S_CADASTRO",13);
  define("S_PESQUISA",14);
  define("S_CADASTRO_DEFICIENCIA", 15);
  define("S_PESQUISA_DEFICIENCIA", 16);
  define("S_PESQUISA_SECRETARIA", 17);
  define("S_CADASTRO_SECRETARIA", 18);
  define("S_ALTERACAO_DEFICIENCIA", 19);
  define("S_ALTERACAO_SECRETARIA", 20);
  define("S_RELATORIO", 21);
  define("S_CADASTRO_EMPRESA", 22);
  define("S_PESQUISA_EMPRESA", 25);
  define("S_ALTERACAO_EMPRESA", 24);
  define("S_LOG_ACESSO", 26);
  define("S_AlTERACAO_CANDIDATO_DEFICIENCIA", 27);
  define("S_SINALIZAR_ADMISSAO", 28);
  define("S_RELATORIO_ADMISSAO", 29);
  define("S_RELATORIO_VAGA",30);
  define("S_RELATORIO_ESTATISTICAS",31);
  define("S_EMAIL",32);
  define("S_COORDENADORIA",33);
  define("S_VISUALIZAR_EMP",34);
  define("S_CONFIGURACAO",35);
  define("S_CADASTRO_TEXTOS",36);
  define("S_CADASTRO_IMAGENS",37);
  define("S_CADASTRO_FAQ",38);
  define("S_RELATORIO_PERIODO", 39);
  
?>
